#ifndef GLOBALCONFIG_H
#define GLOBALCONFIG_H

#define CONNECTIONS_FILE "connections.xml"
#define LIVESTATUS_HOST_KEY "name"

#define FIELD_SEPARATOR_STRING "126"
#define FIELD_SEPARATOR_CHAR '~'
#define DATASET_SEPARATOR_STRING "10"
#define DATASET_SEPARATOR_CHAR '\n'
#define LIST_SEPARATOR_STRING "44"
#define LIST_SEPARATOR_CHAR ","
#define HOST_SERVICE_SEPARATOR_STRING "124"
#define HOST_SERVICE_SEPARATOR_CHAR "|"


#endif // GLOBALCONFIG_H
